version: '3.1'

services:

  drupal:
    image: drupal:8.6.4-apache 
    ports:
      - 8080:80
    volumes:
      - drupal-modules:/var/www/html/modules 
      - drupal-profiles:/var/www/html/profiles 
      - drupal-sites:/var/www/html/sites 
      - drupal-themes:/var/www/html/themes
      
  postgres:
    image: postgres:11.1-alpine
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/psql-password
    secrets: 
      - psql-password
    volumes:
      - drupal-data:/var/lib/postgresql/data
      
volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
  drupal-data:

secrets:
  psql-password:
    external: true