version: '3'

services:

  drupal:
    build: .
    image: custom-drupal 
    ports:
      - 8080:80
    volumes:
      - drupal-modules:/var/www/html/modules 
      - drupal-profiles:/var/www/html/profiles 
      - drupal-sites:/var/www/html/sites 
      - drupal-themes:/var/www/html/themes
      
  postgres:
    image: postgres:11.1-alpine
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - drupal-data:/var/lib/postgresql/data
      
volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
  drupal-data: